#!/bin/bash

repo=/root/atmoz-net.git
work=/root/atmoz-net
target=/usr/share/nginx/html

rm -rf $work
mkdir $work
git --work-tree=$work --git-dir=$repo checkout -f

rm -rf $target
mkdir $target
/root/go/bin/ply --include-markdown $work $target

